<script lang="ts">
  import '../app.css'; import { base } from '$app/paths'; import { page } from '$app/state'; import { onMount,type Snippet } from 'svelte'; import Logo from '$lib/components/site/Logo.svelte'; import Icon from '$lib/components/site/Icon.svelte'; import CommandPalette from '$lib/components/site/CommandPalette.svelte'; import { sections,guides,componentIndex,REPOSITORY,sectionOf } from '$lib/site/nav.js'; import {theme} from '$lib/site/theme.svelte.js';
  let {children}:{children:Snippet}=$props(); let paletteOpen=$state(false);let drawerOpen=$state(false);let shortcut=$state('Ctrl K');const path=$derived(page.url.pathname.replace(base,'')||'/');const home=$derived(path==='/');const active=$derived(sectionOf(path));
  const rail=$derived(active==='components'?componentIndex.map(x=>({label:x.title,href:`/components/${x.name}/`})):guides.map(x=>({label:x.title,href:`/docs/${x.slug}/`})));
  onMount(()=>{theme.sync();if(/mac|iphone|ipad/i.test(navigator.platform))shortcut='⌘K'});
</script>
<svelte:head><meta name="description" content="Svelte-5-Komponenten für deterministische Open-Graph-Bilder mit Satori"/></svelte:head>
<CommandPalette bind:open={paletteOpen} {base}/><a href="#content" class="sr-only focus:fixed focus:z-50 focus:bg-foreground focus:px-4 focus:py-2 focus:text-background">Zum Inhalt</a>
<div class="flex min-h-screen flex-col"><header class="bg-background/90 sticky top-0 z-40 border-b backdrop-blur"><div class="container-page flex h-14 items-center gap-3"><a href={`${base}/`} class="flex items-center gap-2.5 no-underline"><Logo class="size-7"/><span class="display hidden text-[15px] sm:inline">ogimagecn-svelte</span></a><nav class="ml-6 hidden gap-1 md:flex">{#each sections as s}<a href={`${base}${s.href}`} class={`rounded px-2.5 py-1.5 text-sm no-underline ${!home&&active===s.id?'font-medium text-foreground':'text-muted-foreground hover:text-foreground'}`}>{s.label}</a>{/each}</nav><div class="ml-auto flex items-center gap-1"><button onclick={()=>paletteOpen=true} class="text-muted-foreground flex h-8 items-center gap-2 rounded border px-2.5 text-sm sm:w-56"><Icon name="search"/><span class="hidden flex-1 text-left sm:inline">Suchen</span><kbd class="hidden font-mono text-[11px] sm:inline">{shortcut}</kbd></button><button onclick={()=>theme.toggle()} aria-label="Farbschema wechseln" class="hover:bg-accent grid size-8 place-items-center rounded"><Icon name={theme.dark?'moon':'sun'}/></button><a href={REPOSITORY} aria-label="GitHub" class="hover:bg-accent grid size-8 place-items-center rounded"><Icon name="github"/></a>{#if !home}<button onclick={()=>drawerOpen=!drawerOpen} class="grid size-8 place-items-center lg:hidden" aria-label="Navigation öffnen"><Icon name={drawerOpen?'x':'menu'}/></button>{/if}</div></div></header>
{#if home}<main id="content" class="flex-1">{@render children()}</main>{:else}<div class="container-page flex flex-1 gap-10"><aside class="hidden w-56 shrink-0 border-r lg:block"><div class="sticky top-14 max-h-[calc(100vh-3.5rem)] overflow-y-auto py-8 pr-4"><p class="field-label text-muted-foreground mb-4">{active==='components'?'Vorlagen':'Anleitungen'}</p><nav class="flex flex-col">{#each rail as link}<a href={`${base}${link.href}`} class={`border-l-2 py-1 pl-3 text-[13.5px] no-underline ${path===link.href?'border-l-primary font-medium':'border-l-transparent text-muted-foreground hover:text-foreground'}`}>{link.label}</a>{/each}</nav></div></aside><main id="content" class="min-w-0 flex-1 py-10">{@render children()}</main></div>{#if drawerOpen}<nav class="bg-background fixed inset-x-0 top-14 bottom-0 z-30 overflow-y-auto border-t p-6 lg:hidden">{#each rail as link}<a href={`${base}${link.href}`} class="block border-l-2 px-4 py-2 text-sm">{link.label}</a>{/each}</nav>{/if}{/if}
<footer class="mt-20 border-t"><div class="container-page flex flex-col gap-8 py-10 sm:flex-row"><div class="max-w-sm"><a href={`${base}/`} class="flex items-center gap-2.5 no-underline"><Logo class="size-6"/><span class="display">ogimagecn-svelte</span></a><p class="text-muted-foreground mt-3 text-sm">MIT-lizenziert. Die Bilder werden lokal und deterministisch gerendert — ohne Browser-Screenshots.</p></div><div class="ml-auto grid grid-cols-2 gap-12">{#each sections as s}<div><p class="field-label text-muted-foreground">{s.label}</p><a href={`${base}${s.href}`} class="text-muted-foreground mt-2 block text-sm">Alle {s.count} öffnen</a></div>{/each}</div></div><div class="container-page flex items-center border-t py-4 text-sm text-muted-foreground"><span class="font-mono text-[11px]">X-Renderer: Svelte 5 · Satori · resvg</span><a class="ml-auto" href={REPOSITORY}>GitHub</a></div></footer></div>
