import { cp, mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { join, resolve } from "node:path";
import { createServer } from "vite";
import { components, defaultOrigin } from "./registry-metadata.mjs";

await import("./build-registry.mjs");

const root = resolve(import.meta.dirname, "..");
const output = join(root, "docs", "build");
const previewDir = join(output, "previews");
const origin = (process.env.DOCS_ORIGIN || defaultOrigin).replace(/\/$/, "");
const basePath = `/${(process.env.DOCS_BASE_PATH || "ogimagecn-svelte").replace(/^\/+|\/+$/g, "")}`;

function exportName(name) {
  return name.split("-").map((part) => part[0].toUpperCase() + part.slice(1)).join("");
}

function escapeHtml(value) {
  return value.replace(/[&<>"']/g, (character) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;"
  })[character]);
}

await rm(output, { recursive: true, force: true });
await mkdir(previewDir, { recursive: true });
await cp(join(root, "docs", "static"), output, { recursive: true });
await cp(join(root, "src", "lib", "fonts"), join(output, "fonts"), { recursive: true });

const vite = await createServer({ root, server: { middlewareMode: true }, appType: "custom" });
const cards = [];
try {
  const library = await vite.ssrLoadModule("/src/lib/index.ts");
  for (const metadata of components) {
    const name = exportName(metadata.name);
    const component = library[name];
    if (!component) throw new Error(`The public package does not export ${name}`);
    const deterministicProps = metadata.name === "owner"
      ? { images: [], logo: "" }
      : metadata.name === "shiori" ? { logo: "" } : {};
    const rendered = await library.renderImage(component, deterministicProps);
    await writeFile(join(previewDir, `${metadata.name}.svg`), rendered.svg);
    await writeFile(join(previewDir, `${metadata.name}.png`), rendered.png);
    cards.push(`<article id="${metadata.name}" class="card">
    <a href="./previews/${metadata.name}.png"><img src="./previews/${metadata.name}.png" width="600" height="315" loading="lazy" alt="${escapeHtml(metadata.title)} generated Open Graph image"></a>
    <div class="card-copy"><h2>${escapeHtml(metadata.title)}</h2><p>${escapeHtml(metadata.description)}</p>
    <code>pnpm dlx shadcn-svelte@latest add ${origin}/r/${metadata.name}.json</code></div>
  </article>`);
  }
} finally {
  await vite.close();
}

const html = `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>ogimagecn-svelte</title><meta name="description" content="Svelte 5 Open Graph image components rendered by Satori.">
<link rel="canonical" href="${origin}/"><style>
:root{color-scheme:dark;font-family:Inter,ui-sans-serif,system-ui,sans-serif;background:#09090b;color:#fafafa}*{box-sizing:border-box}body{margin:0}main{width:min(1180px,calc(100% - 32px));margin:auto;padding:72px 0}.hero{max-width:800px;margin-bottom:56px}.eyebrow{color:#a1a1aa;text-transform:uppercase;letter-spacing:.16em;font-size:12px}h1{font-size:clamp(42px,8vw,82px);line-height:.95;letter-spacing:-.055em;margin:14px 0 24px}p{color:#a1a1aa;line-height:1.6}.meta{font-size:14px}.gallery{display:grid;grid-template-columns:repeat(auto-fit,minmax(min(100%,460px),1fr));gap:28px}.card{overflow:hidden;border:1px solid #27272a;border-radius:16px;background:#111113}.card img{display:block;width:100%;height:auto;aspect-ratio:1200/630;background:#18181b}.card-copy{padding:20px}.card h2{margin:0 0 6px;font-size:20px}.card p{margin:0 0 18px}.card code{display:block;overflow:auto;padding:12px;border-radius:8px;background:#09090b;color:#d4d4d8;font-size:12px;white-space:nowrap}a{color:inherit}.notice{border-left:2px solid #52525b;padding-left:16px}footer{padding-top:56px;color:#71717a;font-size:13px}
</style></head><body><main><section class="hero"><div class="eyebrow">Svelte 5 · Satori · SVG + PNG</div><h1>Open Graph images, without React.</h1><p>Typed, composable Svelte components that render through Satori. Every gallery image below is generated by the package's production SVG and PNG pipeline.</p><p class="meta notice">GitHub Pages base path: <code>${basePath}</code>. All routes, preview images, and registry links are project-path safe.</p></section><section class="gallery">${cards.join("\n")}</section><footer>Upstream parity is pinned and documented in UPSTREAM.md. Registry catalog: <a href="./r/registry.json">r/registry.json</a>.</footer></main></body></html>`;

await writeFile(join(output, "index.html"), html);
await writeFile(join(output, ".nojekyll"), "");
console.log(`Built docs with ${components.length} final PNG and SVG previews at ${basePath}/`);
